name: Deploy to Firebase
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.73.0"

      - name: Build Static HTML
        run: hugo
        
      - name: Install Dependencies
        run: npm install

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:weddingbeach
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
